# Generated by Django 3.2 on 2021-04-24 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_reporter', '0002_alter_news_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Date_reported',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
