# Generated by Django 3.2 on 2021-04-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_reporter', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
