# Generated by Django 3.2 on 2021-04-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_reporter', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Date_reported',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
